name: AXDA-ScriptEngine
main: net.axda.se.AXDAScriptEngine
version: ${project.version}
api:
  - '1.0.0'
  - 'Nukkit-MOT'
load: STARTUP
softdepend:
  - AXDA-Kernel
  - EconomyAPI
author: Ruok
description: AXDA ScriptEngine
website: https://axda.net/